### ISSUE TITLE
tiebreaker question show answer screen - has the player the question was about as having answered the question (screenshot attached)

### ISSUE THREAD

**Issue by matandon** [hto-projects/friendivia#237]
![Image](https://user-images.githubusercontent.com/115041077/254586725-27389138-6e90-4e0c-9ff6-7873fdb1c573.png)

**Comment by josephmaxwellhyland** [comment]
tiebreaker has changed - so this may no longer apply.

#223 appears to be a similar issue - closing this as a duplicate.
