### ISSUE TITLE
Improve the "About" landing page

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendivia#375]
This page will be the first impression a potential host would see - the link we would share out to all of Hyland, or to anyone else who wants to learn about it. It should represent the brand well, have a simple, clear description of the game, and inspire anyone who sees it to want to play the game.

**Comment by josephmaxwellhyland** [comment]
not live yet on friendivia.com yet, but https://frdv.onrender.com/about/ should work
